config/routes.rb
Rails.application.routes.draw do
  resources :hello_worlds
  # root hello world index
  root "hello_worlds#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # root "www#index"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hello_world.rb
class HelloWorld < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_worlds_controller.rb
class HelloWorldsController < ApplicationController
  before_action :set_hello_world, only: [:show, :edit, :update, :destroy]

  # GET /hello_worlds
  def index
    @hello_worlds = HelloWorld.all
  end

  # GET /hello_worlds/1
  def show
  end

  # GET /hello_worlds/new
  def new
    @hello_world = HelloWorld.new
  end

  # GET /hello_worlds/1/edit
  def edit
  end

  # POST /hello_worlds
  def create
    @hello_world = HelloWorld.new(hello_world_params)
    if @hello_world.save
      redirect_to hello_worlds_path, notice: 'Hello world was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /hello_worlds/1
  def update
    if @hello_world.update(hello_world_params)
      redirect_to hello_worlds_path, notice: 'Hello world was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /hello_worlds/1
  def destroy
    @hello_world.destroy
    redirect_to hello_worlds_url, notice: 'Hello world was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hello_world
      @hello_world = HelloWorld.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hello_world_params
      params.require(:hello_world).permit(:message)
    end
end

app/controllers/www_controller.rb
class WwwController < ApplicationController
    def index
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_worlds_helper.rb
module HelloWorldsHelper
end

app/views/hello_worlds/_form.html.erb
<%= form_with(model: hello_world, local: true) do |form| %>
  <% if hello_world.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hello_world.errors.count, "error") %> prohibited this hello_world from being saved:</h2>

      <ul>
        <% hello_world.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hello_worlds/edit.html.erb
<h1>Edit Hello World</h1>

<%= render 'form', hello_world: @hello_world %>

<%= link_to 'Back', hello_worlds_path %>

app/views/hello_worlds/index.html.erb
<h1>Hello Worlds</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hello_worlds.each do |hello_world| %>
      <tr>
        <td><%= hello_world.message %></td>
        <td><%= link_to 'Show', hello_world %></td>
        <td><%= link_to 'Edit', edit_hello_world_path(hello_world) %></td>
        <td><%= link_to 'Destroy', hello_world, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hello World', new_hello_world_path %>

app/views/hello_worlds/new.html.erb
<h1>New Hello World</h1>

<%= render 'form', hello_world: @hello_world %>

<%= link_to 'Back', hello_worlds_path %>

app/views/hello_worlds/show.html.erb
<h1>HelloWorlds#show</h1>
<p>Find me in app/views/hello_worlds/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KamalExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/www/index.html.erb
Hellooooo <%= ENV["HELLO"] %>.